POST http://localhost:5001/product-carts
Content-Type: application/json

{
  "userId": 1,
  "productCartItems": [
    {
      "productId": 23,
      "quantity": 2
    },
    {
      "productId": 12,
      "quantity": 4
    },
    {
      "productId": 8,
      "quantity": 1
    }
  ]
}

### Example Usage
# A sample payload for creating a ProductCart
POST http://localhost:5001/product-carts
Content-Type: application/json

{
  "userId": 2,
  "productCartItems": [
    {
      "productId": 120,
      "quantity": 5
    },
    {
      "productId": 121,
      "quantity": 3
    }
  ]
}