DELETE http://localhost:5001/product-carts/{{productCartId}}
Content-Type: application/json

### Example Usage
# To test with a specific ProductCart id:
DELETE http://localhost:5001/product-carts/8287eaa7-9b25-4272-9a43-9855098f68fd